{{- if and .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "zabbix-server"
  labels:
    app: zabbix
  namespace: zabbix
{{- if .Values.server.service.annotations }}
  annotations:
  {{ toYaml .Values.server.service.annotations | nindent 4 }}
{{- end }}
spec:
  ports:
  - port: 10051
    targetPort: 10051
    protocol: TCP
    name: "zabbix-trapper"
  {{- if .Values.server.snmptraps.enabled }}
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: "snmp-trap"
  {{- end }}
{{- if .Values.server.service.loadBalancerIP }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.server.service.loadBalancerIP }}
{{- else }}
  clusterIP: None
{{- end }}
  selector:
    app.kubernetes.io/name:     zabbix-server
    app.kubernetes.io/instance: zabbix-server
{{- if .Values.server.service.externalIPs }}
  externalIPs:
  {{- toYaml .Values.server.service.externalIPs | nindent 8 }}
{{- end }}
{{- end }}
